version: "3.9"
services:
  api:
    build: .
    ports:
      - "3030:3030"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/api'
    depends_on:
      - mongo
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"